(function(){
  const PK=window.PuzzleKit;
  const diff=i=>i<3?'Beginner':i<6?'Normaal':i<9?'Moeilijk':'Expert';
  function createGame(def,levels,playImpl){
    let cleanup=()=>{};
    def.levelCount=levels.length;
    const launch=()=>{cleanup();cleanup=()=>{};PK.launcher(def,levels,run);};
    const run=(id,opts={})=>{cleanup();cleanup=()=>{};const level=levels.find(l=>l.id===id);if(!level)return launch();cleanup=playImpl(level,opts,launch,run,def)||(()=>{});};
    window.addEventListener('puzzlehub:navigate',()=>{cleanup();cleanup=()=>{};});
    PuzzleHub.registerGame({...def,levelCount:levels.length,open:launch,play:run});
  }
  function timerFor(){const t=PK.timer(s=>{const el=document.getElementById('timer');if(el)el.textContent=PK.fmt(s);});t.start();return t;}
  function tools(items){return `<div class="tool-row logic-tools">${items.map(x=>`<button class="tool" id="${x.id}">${x.icon} <span>${x.label}</span></button>`).join('')}</div>`;}

  /* NONOGRAM */
  const NGRAM_PATTERNS=[
    ['.###.','#####','#####','.###.','..#..'],
    ['#...#','.#.#.','..#..','.#.#.','#...#'],
    ['..#..','.###.','#####','.###.','..#..'],
    ['#####','#...#','#.#.#','#...#','#####'],
    ['..##...','..##...','#######','..##...','..##...','..##...','..##...'],
    ['.#####.','#.....#','#.#.#.#','#.....#','#.###.#','#.....#','.#####.'],
    ['...#...','..###..','.#####.','#######','..###..','..###..','..###..'],
    ['#.....#','##...##','#.#.#.#','#..#..#','#.#.#.#','##...##','#.....#'],
    ['..####..','.######.','###..###','##....##','##....##','###..###','.######.','..####..'],
    ['#......#','.##..##.','..####..','...##...','...##...','..####..','.##..##.','#......#'],
    ['...##...','..####..','.######.','########','##.##.##','...##...','...##...','...##...'],
    ['########','#......#','#.####.#','#.#..#.#','#.#..#.#','#.####.#','#......#','########']
  ];
  function cluesLine(arr){const out=[];let n=0;arr.forEach(v=>{if(v)n++;else if(n){out.push(n);n=0;}});if(n)out.push(n);return out.length?out:[0];}
  const nonogramLevels=NGRAM_PATTERNS.map((rows,i)=>{const mask=rows.flatMap(r=>[...r].map(c=>c==='#')),R=rows.length,C=rows[0].length;return{id:i+1,difficulty:diff(i),rows:R,cols:C,mask,sizeLabel:`${R}×${C}`,rowClues:Array.from({length:R},(_,r)=>cluesLine(mask.slice(r*C,(r+1)*C))),colClues:Array.from({length:C},(_,c)=>cluesLine(Array.from({length:R},(_,r)=>mask[r*C+c])))};});
  createGame({id:'nonogram',name:'Nonogram',tag:'Beeldlogica',icon:'▦',desc:'Kleur vakjes via cijferreeksen en onthul een afbeelding.',longDesc:'De cijfers naast elke rij en kolom vertellen hoe lang aaneengesloten blokken zijn. Vind het verborgen patroon.',rules:['Elke cijferreeks beschrijft groepen gevulde vakjes in die rij of kolom.','Tussen twee groepen zit minstens één leeg vakje.','Tik een vakje om het te vullen; nogmaals om een kruis te zetten; een derde keer maakt het leeg.']},nonogramLevels,(l,opts,launch,run,def)=>{
    const state=Array(l.rows*l.cols).fill(0);let hints=0;const t=timerFor();
    PuzzleHub.app.innerHTML=`<section class="play-shell">${PK.playHeader(l,launch)}<div class="board-wrap"><div class="nonogram-wrap" style="--ng-cols:${l.cols};--ng-rows:${l.rows}"><div></div><div class="ng-col-clues">${l.colClues.map(a=>`<div>${a.map(n=>`<span>${n}</span>`).join('')}</div>`).join('')}</div><div class="ng-row-clues">${l.rowClues.map(a=>`<div>${a.map(n=>`<span>${n}</span>`).join(' ')}</div>`).join('')}</div><div class="ng-grid" id="ngGrid"></div></div></div>${tools([{id:'ngClear',icon:'⌫',label:'Wis alles'},{id:'ngHint',icon:'✦',label:'Hint'}])}</section>`;
    document.getElementById('pkBackPlay').onclick=launch;
    function render(){const host=document.getElementById('ngGrid');host.innerHTML='';state.forEach((v,i)=>{const b=document.createElement('button');b.className=`ng-cell ${v===1?'filled':v===2?'cross':''}`;b.type='button';b.textContent=v===2?'×':'';b.onclick=()=>{state[i]=(state[i]+1)%3;render();check();};host.appendChild(b);});}
    function check(){const rowsOk=Array.from({length:l.rows},(_,r)=>JSON.stringify(cluesLine(Array.from({length:l.cols},(_,c)=>state[r*l.cols+c]===1)))===JSON.stringify(l.rowClues[r])).every(Boolean);const colsOk=Array.from({length:l.cols},(_,c)=>JSON.stringify(cluesLine(Array.from({length:l.rows},(_,r)=>state[r*l.cols+c]===1)))===JSON.stringify(l.colClues[c])).every(Boolean);if(rowsOk&&colsOk)PK.finish(def,l,t.stop(),hints,opts.daily,launch,run);}
    document.getElementById('ngClear').onclick=()=>{state.fill(0);render();};document.getElementById('ngHint').onclick=()=>{let i=l.mask.findIndex((v,j)=>v?state[j]!==1:state[j]===1);if(i<0)i=l.mask.findIndex((v,j)=>!v&&state[j]===0);if(i>=0){state[i]=l.mask[i]?1:2;hints++;render();check();}};render();return()=>t.stop();
  });

  /* BINAIRO */
  function validRows(n){const out=[];for(let m=0;m<(1<<n);m++){const a=Array.from({length:n},(_,i)=>(m>>i)&1);if(a.reduce((x,y)=>x+y,0)!==n/2)continue;let ok=true;for(let i=0;i<n-2;i++)if(a[i]===a[i+1]&&a[i]===a[i+2])ok=false;if(ok)out.push(a);}return out;}
  function binSolution(n,seed){const rows=validRows(n),rand=PK.rng(seed),order=[...rows].sort(()=>rand()-.5),grid=[];function bt(r){if(r===n){const cols=Array.from({length:n},(_,c)=>grid.map(x=>x[c]).join(''));return new Set(cols).size===n;}for(const row of order){if(grid.some(x=>x.every((v,i)=>v===row[i])))continue;let ok=true;for(let c=0;c<n;c++){const ones=grid.reduce((s,x)=>s+x[c],0)+row[c];if(ones>n/2||r+1-ones>n/2){ok=false;break;}if(r>=2&&grid[r-1][c]===row[c]&&grid[r-2][c]===row[c]){ok=false;break;}}if(!ok)continue;grid.push(row);if(bt(r+1))return true;grid.pop();}return false;}bt(0);return grid.flat();}
  const binLevels=Array.from({length:12},(_,i)=>{const n=i<4?6:8,solution=binSolution(n,700+i*19),rand=PK.rng(900+i),ratio=[.58,.54,.5,.48,.46,.44,.42,.40,.38,.36,.34,.32][i],clues={};solution.forEach((v,j)=>{if(rand()<ratio)clues[j]=v;});return{id:i+1,difficulty:diff(i),n,solution,clues,sizeLabel:`${n}×${n}`};});
  createGame({id:'binairo',name:'Binairo',tag:'Binaire logica',icon:'01',desc:'Nullen en enen, zonder drie dezelfde op rij.',longDesc:'Vul een vierkant raster met 0 en 1. De simpele regels grijpen steeds verder in elkaar.',rules:['Iedere rij en kolom bevat evenveel nullen als enen.','Nooit drie gelijke cijfers direct naast of onder elkaar.','Geen twee volledige rijen of kolommen mogen identiek zijn.']},binLevels,(l,opts,launch,run,def)=>{
    const vals=Array(l.n*l.n).fill(null);Object.entries(l.clues).forEach(([i,v])=>vals[+i]=v);let hints=0;const t=timerFor();
    PuzzleHub.app.innerHTML=`<section class="play-shell">${PK.playHeader(l)}<div class="board-wrap"><div class="binary-grid" id="binaryGrid" style="--n:${l.n}"></div></div>${tools([{id:'binClear',icon:'⌫',label:'Wissen'},{id:'binHint',icon:'✦',label:'Hint'}])}</section>`;document.getElementById('pkBackPlay').onclick=launch;
    function render(){const h=document.getElementById('binaryGrid');h.innerHTML='';vals.forEach((v,i)=>{const fixed=i in l.clues,b=document.createElement('button');b.type='button';b.className=`binary-cell ${fixed?'fixed':''}`;b.textContent=v===null?'':v;b.disabled=fixed;if(!fixed)b.onclick=()=>{vals[i]=v===null?0:v===0?1:null;render();check();};h.appendChild(b);});}
    function check(){if(vals.some(v=>v===null))return;const n=l.n,rows=Array.from({length:n},(_,r)=>vals.slice(r*n,(r+1)*n)),cols=Array.from({length:n},(_,c)=>Array.from({length:n},(_,r)=>vals[r*n+c]));const validLine=a=>a.reduce((x,y)=>x+y,0)===n/2&&!a.some((v,i)=>i<n-2&&v===a[i+1]&&v===a[i+2]);if(rows.every(validLine)&&cols.every(validLine)&&new Set(rows.map(a=>a.join(''))).size===n&&new Set(cols.map(a=>a.join(''))).size===n)PK.finish(def,l,t.stop(),hints,opts.daily,launch,run);}
    document.getElementById('binClear').onclick=()=>{vals.forEach((_,i)=>{if(!(i in l.clues))vals[i]=null;});render();};document.getElementById('binHint').onclick=()=>{const i=vals.findIndex((v,j)=>!(j in l.clues)&&v!==l.solution[j]);if(i>=0){vals[i]=l.solution[i];hints++;render();check();}};render();return()=>t.stop();
  });

  /* HASHI */
  function hashiLevel(id){const i=id-1,rr=i<6?3:4,cc=i<9?3:4,rand=PK.rng(1200+id),nodes=[];for(let r=0;r<rr;r++)for(let c=0;c<cc;c++)nodes.push({r:r*2,c:c*2});const candidates=[];for(let r=0;r<rr;r++)for(let c=0;c<cc;c++){const a=r*cc+c;if(c+1<cc)candidates.push([a,a+1]);if(r+1<rr)candidates.push([a,a+cc]);}const parent=nodes.map((_,i)=>i);const find=x=>parent[x]===x?x:(parent[x]=find(parent[x]));const edges={};[...candidates].sort(()=>rand()-.5).forEach(([a,b])=>{if(find(a)!==find(b)){parent[find(a)]=find(b);edges[`${a}-${b}`]=rand()<.25?2:1;}});candidates.forEach(([a,b])=>{const k=`${a}-${b}`;if(!(k in edges)&&rand()<(.12+i*.012))edges[k]=rand()<.35?2:1;});const counts=nodes.map(()=>0);Object.entries(edges).forEach(([k,w])=>{const [a,b]=k.split('-').map(Number);counts[a]+=w;counts[b]+=w;});return{id,difficulty:diff(i),rr,cc,nodes,candidates,solution:edges,counts,sizeLabel:`${nodes.length} eilanden`};}
  const hashiLevels=Array.from({length:12},(_,i)=>hashiLevel(i+1));
  createGame({id:'hashi',name:'Hashi',tag:'Netwerklogica',icon:'≋',desc:'Verbind eilanden met één of twee bruggen.',longDesc:'Elk eiland geeft aan hoeveel bruggen eraan vastzitten. Verbind alle eilanden tot één netwerk zonder kruisingen.',rules:['Bruggen lopen alleen horizontaal of verticaal naar het eerstvolgende eiland.','Tussen twee eilanden lopen maximaal twee bruggen.','Het cijfer op een eiland is het totale aantal bruggen eraan; alle eilanden vormen samen één netwerk.']},hashiLevels,(l,opts,launch,run,def)=>{
    const vals={};l.candidates.forEach(([a,b])=>vals[`${a}-${b}`]=0);let hints=0;const t=timerFor();const gridN=Math.max(l.rr,l.cc)*2-1;
    PuzzleHub.app.innerHTML=`<section class="play-shell">${PK.playHeader(l)}<div class="board-wrap"><div class="hashi-grid" id="hashiGrid" style="--hr:${l.rr*2-1};--hc:${l.cc*2-1}"></div></div>${tools([{id:'hashiClear',icon:'⌫',label:'Wis bruggen'},{id:'hashiHint',icon:'✦',label:'Hint'}])}</section>`;document.getElementById('pkBackPlay').onclick=launch;
    function render(){const host=document.getElementById('hashiGrid');host.innerHTML='';for(let gr=0;gr<l.rr*2-1;gr++)for(let gc=0;gc<l.cc*2-1;gc++){const el=document.createElement('div');el.style.gridRow=gr+1;el.style.gridColumn=gc+1;if(gr%2===0&&gc%2===0){const ni=(gr/2)*l.cc+(gc/2);el.className='hashi-island';const used=l.candidates.reduce((s,[a,b])=>s+((a===ni||b===ni)?vals[`${a}-${b}`]:0),0);el.innerHTML=`<b>${l.counts[ni]}</b><small>${used}</small>`;}else if(gr%2===0&&gc%2===1){const r=gr/2,c=(gc-1)/2,a=r*l.cc+c,b=a+1,k=`${a}-${b}`,bt=document.createElement('button');bt.className='hashi-edge horizontal';bt.type='button';bt.textContent=vals[k]===1?'━':vals[k]===2?'═':'';bt.onclick=()=>{vals[k]=(vals[k]+1)%3;render();check();};el.appendChild(bt);}else if(gr%2===1&&gc%2===0){const r=(gr-1)/2,c=gc/2,a=r*l.cc+c,b=a+l.cc,k=`${a}-${b}`,bt=document.createElement('button');bt.className='hashi-edge vertical';bt.type='button';bt.textContent=vals[k]===1?'┃':vals[k]===2?'║':'';bt.onclick=()=>{vals[k]=(vals[k]+1)%3;render();check();};el.appendChild(bt);}host.appendChild(el);}}
    function check(){const used=l.nodes.map(()=>0);l.candidates.forEach(([a,b])=>{used[a]+=vals[`${a}-${b}`];used[b]+=vals[`${a}-${b}`];});if(!used.every((v,i)=>v===l.counts[i]))return;const seen=new Set([0]),q=[0];while(q.length){const a=q.pop();l.candidates.forEach(([x,y])=>{const w=vals[`${x}-${y}`];if(!w)return;const b=x===a?y:y===a?x:null;if(b!==null&&!seen.has(b)){seen.add(b);q.push(b);}});}if(seen.size===l.nodes.length)PK.finish(def,l,t.stop(),hints,opts.daily,launch,run);}
    document.getElementById('hashiClear').onclick=()=>{Object.keys(vals).forEach(k=>vals[k]=0);render();};document.getElementById('hashiHint').onclick=()=>{const k=Object.keys(vals).find(k=>vals[k]!== (l.solution[k]||0));if(k){vals[k]=l.solution[k]||0;hints++;render();check();}};render();return()=>t.stop();
  });

  /* SLITHERLINK */
  function slitherLevel(id){const i=id-1,n=i<4?4:i<8?5:6,rand=PK.rng(2100+id),left=[],right=[];let l=Math.floor(n/2)-1,r=Math.floor(n/2)+1;for(let y=0;y<n;y++){if(y===0||rand()<.5)l=Math.max(0,Math.min(n-2,l+(rand()<.5?-1:1)));if(y===0||rand()<.5)r=Math.min(n-1,Math.max(l+1,r+(rand()<.5?-1:1)));left.push(l);right.push(r);}const inside=(y,x)=>y>=0&&y<n&&x>=left[y]&&x<=right[y];const sol=new Set();for(let y=0;y<n;y++)for(let x=left[y];x<=right[y];x++){if(!inside(y-1,x))sol.add(`H:${y}:${x}`);if(!inside(y+1,x))sol.add(`H:${y+1}:${x}`);if(x===left[y])sol.add(`V:${y}:${x}`);if(x===right[y])sol.add(`V:${y}:${x+1}`);}const clues={};for(let y=0;y<n;y++)for(let x=0;x<n;x++){const cnt=[`H:${y}:${x}`,`H:${y+1}:${x}`,`V:${y}:${x}`,`V:${y}:${x+1}`].filter(k=>sol.has(k)).length;if(rand()<(.82-i*.035))clues[`${y},${x}`]=cnt;}return{id,difficulty:diff(i),n,solution:[...sol],clues,sizeLabel:`${n}×${n}`};}
  const slitherLevels=Array.from({length:12},(_,i)=>slitherLevel(i+1));
  createGame({id:'slitherlink',name:'Slitherlink',tag:'Lijnen',icon:'∞',desc:'Teken precies één gesloten lus langs de cijfers.',longDesc:'Verbind lijnstukken rond de vakjes tot één enkele lus. De cijfers vertellen hoeveel zijden van dat vakje onderdeel van de lus zijn.',rules:['Een cijfer geeft aan hoeveel van de vier randen van dat vakje lijn zijn.','De uiteindelijke lijn vormt precies één gesloten lus en vertakt nergens.','Tik een rand voor een lijn, nogmaals voor een kruis en nogmaals om hem leeg te maken.']},slitherLevels,(l,opts,launch,run,def)=>{
    const state={};let hints=0;const t=timerFor(),sol=new Set(l.solution);
    PuzzleHub.app.innerHTML=`<section class="play-shell">${PK.playHeader(l)}<div class="board-wrap"><div class="slither-grid" id="slitherGrid" style="--sn:${l.n};--sgrid:${l.n*2+1}"></div></div>${tools([{id:'slClear',icon:'⌫',label:'Wis alles'},{id:'slHint',icon:'✦',label:'Hint'}])}</section>`;document.getElementById('pkBackPlay').onclick=launch;
    function cycle(k){state[k]=((state[k]||0)+1)%3;render();check();}
    function render(){const h=document.getElementById('slitherGrid');h.innerHTML='';for(let gy=0;gy<l.n*2+1;gy++)for(let gx=0;gx<l.n*2+1;gx++){let el;if(gy%2===0&&gx%2===0){el=document.createElement('span');el.className='sl-dot';el.textContent='•';}else if(gy%2===0&&gx%2===1){const k=`H:${gy/2}:${(gx-1)/2}`;el=document.createElement('button');el.type='button';el.className=`sl-edge h ${state[k]===1?'line':state[k]===2?'x':''}`;el.textContent=state[k]===2?'×':'';el.onclick=()=>cycle(k);}else if(gy%2===1&&gx%2===0){const k=`V:${(gy-1)/2}:${gx/2}`;el=document.createElement('button');el.type='button';el.className=`sl-edge v ${state[k]===1?'line':state[k]===2?'x':''}`;el.textContent=state[k]===2?'×':'';el.onclick=()=>cycle(k);}else{const y=(gy-1)/2,x=(gx-1)/2;el=document.createElement('span');el.className='sl-clue';el.textContent=l.clues[`${y},${x}`]??'';}el.style.gridRow=gy+1;el.style.gridColumn=gx+1;h.appendChild(el);}}
    function check(){const lines=Object.keys(state).filter(k=>state[k]===1);if(!lines.length)return;for(const [key,num] of Object.entries(l.clues)){const [y,x]=key.split(',').map(Number),cnt=[`H:${y}:${x}`,`H:${y+1}:${x}`,`V:${y}:${x}`,`V:${y}:${x+1}`].filter(k=>state[k]===1).length;if(cnt!==num)return;}const adj=new Map();const add=(a,b)=>{if(!adj.has(a))adj.set(a,[]);adj.get(a).push(b);};for(const k of lines){const [d,a,b]=k.split(':'),r=+a,c=+b;let v1,v2;if(d==='H'){v1=`${r},${c}`;v2=`${r},${c+1}`;}else{v1=`${r},${c}`;v2=`${r+1},${c}`;}add(v1,v2);add(v2,v1);}if([...adj.values()].some(a=>a.length!==2))return;const start=[...adj.keys()][0],seen=new Set([start]),q=[start];while(q.length){const v=q.pop();for(const n of adj.get(v)||[])if(!seen.has(n)){seen.add(n);q.push(n);}}if(seen.size===adj.size)PK.finish(def,l,t.stop(),hints,opts.daily,launch,run);}
    document.getElementById('slClear').onclick=()=>{Object.keys(state).forEach(k=>delete state[k]);render();};document.getElementById('slHint').onclick=()=>{const all=[];for(let y=0;y<=l.n;y++)for(let x=0;x<l.n;x++)all.push(`H:${y}:${x}`);for(let y=0;y<l.n;y++)for(let x=0;x<=l.n;x++)all.push(`V:${y}:${x}`);const k=all.find(k=>(state[k]===1)!==sol.has(k));if(k){state[k]=sol.has(k)?1:2;hints++;render();check();}};render();return()=>t.stop();
  });

  /* KAKURO */
  const KAKURO_BLOCKS=[[[1,1,2,2],[1,4,2,6],[4,1,6,3],[4,5,6,6]],[[1,1,3,2],[1,4,2,6],[4,1,6,3],[4,5,6,6]],[[1,1,2,3],[1,5,3,6],[4,1,6,2],[4,4,6,6]]];
  function kakuroLevel(id){const i=id-1,n=7,blocks=KAKURO_BLOCKS[i%KAKURO_BLOCKS.length],white=Array(n*n).fill(false),solution=Array(n*n).fill(null),rand=PK.rng(3100+id),perm=[1,2,3,4,5,6,7,8,9].sort(()=>rand()-.5);blocks.forEach(([r1,c1,r2,c2],bi)=>{for(let r=r1;r<=r2;r++)for(let c=c1;c<=c2;c++){white[r*n+c]=true;solution[r*n+c]=perm[((r-r1)*3+(c-c1)+bi*2)%9];}});const clues={};function add(r,c,type,sum){const k=`${r},${c}`;if(!clues[k])clues[k]={};clues[k][type]=sum;}for(let r=0;r<n;r++){let c=0;while(c<n){if(!white[r*n+c]){c++;continue;}const s=c,arr=[];while(c<n&&white[r*n+c]){arr.push(solution[r*n+c]);c++;}if(arr.length>=2)add(r,s-1,'right',arr.reduce((a,b)=>a+b,0));}}for(let c=0;c<n;c++){let r=0;while(r<n){if(!white[r*n+c]){r++;continue;}const s=r,arr=[];while(r<n&&white[r*n+c]){arr.push(solution[r*n+c]);r++;}if(arr.length>=2)add(s-1,c,'down',arr.reduce((a,b)=>a+b,0));}}return{id,difficulty:diff(i),n,white,solution,clues,sizeLabel:'7×7'};}
  const kakuroLevels=Array.from({length:12},(_,i)=>kakuroLevel(i+1));
  createGame({id:'kakuro',name:'Kakuro',tag:'Rekenlogica',icon:'+',desc:'Een cijferkruiswoord met sommen.',longDesc:'Vul cijfers 1–9 in de witte vakjes. De somaanwijzingen gelden voor een horizontale of verticale reeks.',rules:['Elke aanwijzing is de som van de aansluitende witte reeks.','Binnen één reeks mag een cijfer 1–9 niet dubbel voorkomen.','Kruisende horizontale en verticale sommen delen hetzelfde cijfer.']},kakuroLevels,(l,opts,launch,run,def)=>{
    const vals=Array(l.n*l.n).fill(null);let selected=null,hints=0;const t=timerFor();
    PuzzleHub.app.innerHTML=`<section class="play-shell">${PK.playHeader(l)}<div class="board-wrap"><div class="kakuro-grid" id="kakuroGrid" style="--kn:${l.n}"></div></div><div class="digit-row nine" id="kdigits"></div>${tools([{id:'kErase',icon:'⌫',label:'Wissen'},{id:'kHint',icon:'✦',label:'Hint'}])}</section>`;document.getElementById('pkBackPlay').onclick=launch;
    function render(){const h=document.getElementById('kakuroGrid');h.innerHTML='';for(let r=0;r<l.n;r++)for(let c=0;c<l.n;c++){const i=r*l.n+c,b=document.createElement('button');b.type='button';if(l.white[i]){b.className=`k-cell white ${selected===i?'selected':''}`;b.textContent=vals[i]??'';b.onclick=()=>{selected=i;render();};}else{b.className='k-cell black';b.disabled=true;const cl=l.clues[`${r},${c}`]||{};b.innerHTML=`<span class="k-down">${cl.down?'↓'+cl.down:''}</span><span class="k-right">${cl.right?'→'+cl.right:''}</span>`;}h.appendChild(b);}}
    function input(n){if(selected===null)return;vals[selected]=n;render();check();}
    function check(){if(l.white.some((w,i)=>w&&vals[i]===null))return;const n=l.n;for(let r=0;r<n;r++){let c=0;while(c<n){if(!l.white[r*n+c]){c++;continue;}const st=c,a=[];while(c<n&&l.white[r*n+c])a.push(vals[r*n+c++]);if(a.length>=2){const cl=l.clues[`${r},${st-1}`]?.right;if(a.reduce((x,y)=>x+y,0)!==cl||new Set(a).size!==a.length)return;}}}for(let c=0;c<n;c++){let r=0;while(r<n){if(!l.white[r*n+c]){r++;continue;}const st=r,a=[];while(r<n&&l.white[r*n+c])a.push(vals[r++*n+c]);if(a.length>=2){const cl=l.clues[`${st-1},${c}`]?.down;if(a.reduce((x,y)=>x+y,0)!==cl||new Set(a).size!==a.length)return;}}}PK.finish(def,l,t.stop(),hints,opts.daily,launch,run);}
    const digs=document.getElementById('kdigits');for(let n=1;n<=9;n++){const b=document.createElement('button');b.className='digit';b.textContent=n;b.onclick=()=>input(n);digs.appendChild(b);}document.getElementById('kErase').onclick=()=>{if(selected!==null){vals[selected]=null;render();}};document.getElementById('kHint').onclick=()=>{let i=l.white.findIndex((w,j)=>w&&vals[j]!==l.solution[j]);if(i>=0){vals[i]=l.solution[i];selected=i;hints++;render();check();}};render();return()=>t.stop();
  });

  /* MINES */
  function neighbors(n,r,c){const a=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const rr=r+dr,cc=c+dc;if(rr>=0&&cc>=0&&rr<n&&cc<n)a.push(rr*n+cc);}return a;}
  function minesSolved(n,mines,start){const M=new Set(mines),rev=new Set(),flags=new Set();function flood(i){const q=[i];while(q.length){const x=q.pop();if(rev.has(x)||M.has(x))continue;rev.add(x);const r=Math.floor(x/n),c=x%n,num=neighbors(n,r,c).filter(j=>M.has(j)).length;if(num===0)neighbors(n,r,c).forEach(j=>{if(!rev.has(j)&&!M.has(j))q.push(j);});}}flood(start);let changed=true;while(changed){changed=false;for(const i of [...rev]){const r=Math.floor(i/n),c=i%n,nb=neighbors(n,r,c),num=nb.filter(j=>M.has(j)).length,unknown=nb.filter(j=>!rev.has(j)&&!flags.has(j)),f=nb.filter(j=>flags.has(j)).length;if(unknown.length&&num===f){unknown.forEach(j=>{const before=rev.size;flood(j);if(rev.size>before)changed=true;});}else if(unknown.length&&num-f===unknown.length){unknown.forEach(j=>{if(!flags.has(j)){flags.add(j);changed=true;}});}}}return rev.size===n*n-M.size;}
  function minesLevel(id){const i=id-1,n=i<4?7:i<8?8:9,count=i<4?7:i<8?10:14,rand=PK.rng(4100+id),start=0;let mines=[];for(let a=0;a<300;a++){const pool=Array.from({length:n*n},(_,x)=>x).filter(x=>x!==start&&!neighbors(n,0,0).includes(x));pool.sort(()=>rand()-.5);mines=pool.slice(0,count);if(minesSolved(n,mines,start))break;}return{id,difficulty:diff(i),n,mines,start,sizeLabel:`${n}×${n} · ${count} mijnen`};}
  const mineLevels=Array.from({length:12},(_,i)=>minesLevel(i+1));
  createGame({id:'mines',name:'Logische mijnen',tag:'Deductie',icon:'✦',desc:'Mijnenveger-levels die vanuit de start logisch oplosbaar zijn.',longDesc:'Open veilige vakjes en markeer mijnen. Deze vaste levels zijn gegenereerd zodat de gegeven start zonder gokwerk kan worden uitgespeeld.',rules:['Een cijfer geeft aan hoeveel mijnen in de acht aangrenzende vakjes liggen.','Gebruik vlaggen voor zekere mijnen en open vakjes die veilig moeten zijn.','Alle veilige vakjes moeten open; raak je een mijn, dan kun je hetzelfde level opnieuw proberen.']},mineLevels,(l,opts,launch,run,def)=>{
    const M=new Set(l.mines),rev=new Set(),flags=new Set();let flagMode=false,hints=0,dead=false;const t=timerFor();
    PuzzleHub.app.innerHTML=`<section class="play-shell">${PK.playHeader(l)}<div class="mine-status"><span id="mineLeft"></span><button class="ghost" id="flagMode">⚑ Vlagmodus</button></div><div class="board-wrap"><div class="mine-grid" id="mineGrid" style="--mn:${l.n}"></div></div>${tools([{id:'mineRestart',icon:'↻',label:'Opnieuw'},{id:'mineHint',icon:'✦',label:'Veilige hint'}])}</section>`;document.getElementById('pkBackPlay').onclick=launch;
    function flood(i){const q=[i];while(q.length){const x=q.pop();if(rev.has(x)||M.has(x)||flags.has(x))continue;rev.add(x);const r=Math.floor(x/l.n),c=x%l.n,num=neighbors(l.n,r,c).filter(j=>M.has(j)).length;if(num===0)neighbors(l.n,r,c).forEach(j=>q.push(j));}}
    function click(i){if(dead||rev.has(i))return;if(flagMode){if(flags.has(i))flags.delete(i);else flags.add(i);}else if(M.has(i)){dead=true;render();PK.modal('Boem',`<div class="win"><div class="win-mark">✦</div><h3>Daar lag een mijn</h3><p>Dit level is zonder gokken oplosbaar. Probeer dezelfde logische route opnieuw.</p></div>`,[{label:'Opnieuw',action:()=>run(l.id,opts),primary:true}]);return;}else flood(i);render();check();}
    function render(){document.getElementById('mineLeft').textContent=`${Math.max(0,M.size-flags.size)} mijnen over`;document.getElementById('flagMode').classList.toggle('active',flagMode);const h=document.getElementById('mineGrid');h.innerHTML='';for(let i=0;i<l.n*l.n;i++){const b=document.createElement('button');b.type='button';const r=Math.floor(i/l.n),c=i%l.n,num=neighbors(l.n,r,c).filter(j=>M.has(j)).length;if(rev.has(i)){b.className='mine-cell revealed';b.textContent=num||'';}else if(dead&&M.has(i)){b.className='mine-cell mine';b.textContent='✦';}else{b.className='mine-cell hidden';b.textContent=flags.has(i)?'⚑':'';b.onclick=()=>click(i);b.oncontextmenu=e=>{e.preventDefault();if(flags.has(i))flags.delete(i);else flags.add(i);render();};}h.appendChild(b);}}
    function check(){if(rev.size===l.n*l.n-M.size)PK.finish(def,l,t.stop(),hints,opts.daily,launch,run);}
    flood(l.start);document.getElementById('flagMode').onclick=()=>{flagMode=!flagMode;render();};document.getElementById('mineRestart').onclick=()=>run(l.id,opts);document.getElementById('mineHint').onclick=()=>{const i=Array.from({length:l.n*l.n},(_,x)=>x).find(x=>!M.has(x)&&!rev.has(x));if(i!==undefined){flood(i);hints++;render();check();}};render();return()=>t.stop();
  });

  /* SUDOKU */
  function sudokuSolved(seed){const rand=PK.rng(seed),base=[...Array(9)].map((_,r)=>[...Array(9)].map((_,c)=>(r*3+Math.floor(r/3)+c)%9+1));const nums=[1,2,3,4,5,6,7,8,9].sort(()=>rand()-.5),map=Object.fromEntries(nums.map((v,i)=>[i+1,v]));let rows=[0,1,2,3,4,5,6,7,8],cols=[0,1,2,3,4,5,6,7,8];for(const g of [0,3,6]){const part=rows.slice(g,g+3).sort(()=>rand()-.5);rows.splice(g,3,...part);const pc=cols.slice(g,g+3).sort(()=>rand()-.5);cols.splice(g,3,...pc);}if(rand()<.5){rows=[...rows.slice(3),...rows.slice(0,3)];}return rows.flatMap(r=>cols.map(c=>map[base[r][c]]));}
  const sudokuLevels=Array.from({length:12},(_,i)=>{const solution=sudokuSolved(5100+i),rand=PK.rng(5200+i),givens=[46,44,42,40,38,36,34,32,30,28,27,26][i],idx=[...Array(81).keys()].sort(()=>rand()-.5).slice(0,givens),clues={};idx.forEach(j=>clues[j]=solution[j]);return{id:i+1,difficulty:diff(i),solution,clues,sizeLabel:'9×9'};});
  createGame({id:'sudoku',name:'Sudoku',tag:'Klassieker',icon:'9',desc:'De klassieker, rustig en zonder poespas.',longDesc:'Vul 1 t/m 9 zodat ieder cijfer precies één keer voorkomt in iedere rij, kolom en elk 3×3-blok.',rules:['Elke rij bevat de cijfers 1 t/m 9 precies één keer.','Elke kolom bevat de cijfers 1 t/m 9 precies één keer.','Ieder dik omlijnd 3×3-blok bevat eveneens 1 t/m 9.']},sudokuLevels,(l,opts,launch,run,def)=>{
    const vals=Array(81).fill(null);Object.entries(l.clues).forEach(([i,v])=>vals[+i]=v);let sel=null,hints=0;const t=timerFor();
    PuzzleHub.app.innerHTML=`<section class="play-shell">${PK.playHeader(l)}<div class="board-wrap"><div class="sudoku-grid" id="sudokuGrid"></div></div><div class="digit-row nine" id="sdigits"></div>${tools([{id:'sErase',icon:'⌫',label:'Wissen'},{id:'sHint',icon:'✦',label:'Hint'}])}</section>`;document.getElementById('pkBackPlay').onclick=launch;
    function render(){const h=document.getElementById('sudokuGrid');h.innerHTML='';vals.forEach((v,i)=>{const b=document.createElement('button');b.type='button';b.className=`sudoku-cell ${i in l.clues?'fixed':''} ${sel===i?'selected':''}`;b.textContent=v??'';if(!(i in l.clues))b.onclick=()=>{sel=i;render();};h.appendChild(b);});}
    function input(n){if(sel===null||sel in l.clues)return;vals[sel]=n;render();check();}
    function check(){if(vals.some(v=>v===null))return;const want='123456789';const ok=a=>[...a].sort().join('')===want;for(let r=0;r<9;r++)if(!ok(vals.slice(r*9,(r+1)*9)))return;for(let c=0;c<9;c++)if(!ok(Array.from({length:9},(_,r)=>vals[r*9+c])))return;for(let br=0;br<3;br++)for(let bc=0;bc<3;bc++){const a=[];for(let r=0;r<3;r++)for(let c=0;c<3;c++)a.push(vals[(br*3+r)*9+bc*3+c]);if(!ok(a))return;}PK.finish(def,l,t.stop(),hints,opts.daily,launch,run);}
    const ds=document.getElementById('sdigits');for(let n=1;n<=9;n++){const b=document.createElement('button');b.className='digit';b.textContent=n;b.onclick=()=>input(n);ds.appendChild(b);}document.getElementById('sErase').onclick=()=>{if(sel!==null&&!(sel in l.clues)){vals[sel]=null;render();}};document.getElementById('sHint').onclick=()=>{const i=vals.findIndex((v,j)=>!(j in l.clues)&&v!==l.solution[j]);if(i>=0){vals[i]=l.solution[i];sel=i;hints++;render();check();}};render();return()=>t.stop();
  });

  /* NURIKABE */
  function seaConnected(n,land){const sea=[];for(let i=0;i<n*n;i++)if(!land.has(i))sea.push(i);if(!sea.length)return false;const seen=new Set([sea[0]]),q=[sea[0]];while(q.length){const x=q.pop(),r=Math.floor(x/n),c=x%n;[[1,0],[-1,0],[0,1],[0,-1]].forEach(([dr,dc])=>{const rr=r+dr,cc=c+dc,j=rr*n+cc;if(rr>=0&&cc>=0&&rr<n&&cc<n&&!land.has(j)&&!seen.has(j)){seen.add(j);q.push(j);}});}return seen.size===sea.length;}
  function nuriLevel(id){const i=id-1,n=i<6?7:9,rand=PK.rng(6100+id),centers=[];for(let r=1;r<n;r+=2)for(let c=1;c<n;c+=2)centers.push(r*n+c);let groups=centers.map(x=>[x]),used=new Set(),tries=Math.min(Math.floor(i/2)+1,Math.floor(centers.length/3));for(let k=0;k<tries;k++){const options=[];centers.forEach((a,ai)=>{if(used.has(a))return;const r=Math.floor(a/n),c=a%n;[[0,2],[2,0]].forEach(([dr,dc])=>{const rr=r+dr,cc=c+dc,b=rr*n+cc;if(rr<n&&cc<n&&centers.includes(b)&&!used.has(b))options.push([a,b,(r+dr/2)*n+(c+dc/2)]);});});if(!options.length)break;const [a,b,mid]=options[Math.floor(rand()*options.length)];used.add(a);used.add(b);groups=groups.filter(g=>!g.includes(a)&&!g.includes(b));groups.push([a,mid,b]);}
    let land=new Set(groups.flat());if(!seaConnected(n,land)){groups=centers.map(x=>[x]);land=new Set(centers);}const clues={};groups.forEach(g=>{const cell=g[Math.floor(rand()*g.length)];clues[cell]=g.length;});return{id,difficulty:diff(i),n,land:[...land],clues,sizeLabel:`${n}×${n}`};}
  const nuriLevels=Array.from({length:12},(_,i)=>nuriLevel(i+1));
  createGame({id:'nurikabe',name:'Nurikabe',tag:'Gebieden',icon:'◫',desc:'Maak eilanden en één aaneengesloten zee.',longDesc:'Cijfers horen bij witte eilanden. Alles daarbuiten wordt zee; de zee moet verbonden blijven en mag nergens een volledig 2×2-blok vormen.',rules:['Elk cijfer hoort bij één wit eiland met precies zoveel vakjes als het cijfer.','Verschillende eilanden raken elkaar niet horizontaal of verticaal.','Alle zwarte zeevakken zijn verbonden en er mag geen 2×2-blok volledig zee zijn.']},nuriLevels,(l,opts,launch,run,def)=>{
    const state=Array(l.n*l.n).fill(0),land=new Set(l.land);let hints=0;Object.keys(l.clues).forEach(i=>state[+i]=2);const t=timerFor();
    PuzzleHub.app.innerHTML=`<section class="play-shell">${PK.playHeader(l)}<div class="board-wrap"><div class="nuri-grid" id="nuriGrid" style="--nn:${l.n}"></div></div>${tools([{id:'nuriClear',icon:'⌫',label:'Wis markeringen'},{id:'nuriHint',icon:'✦',label:'Hint'}])}</section>`;document.getElementById('pkBackPlay').onclick=launch;
    function render(){const h=document.getElementById('nuriGrid');h.innerHTML='';state.forEach((v,i)=>{const fixed=i in l.clues,b=document.createElement('button');b.type='button';b.className=`nuri-cell ${v===1?'sea':v===2?'land':''} ${fixed?'fixed':''}`;b.textContent=fixed?l.clues[i]:(v===1?'':v===2?'·':'');b.disabled=fixed;if(!fixed)b.onclick=()=>{state[i]=(state[i]+1)%3;render();check();};h.appendChild(b);});}
    function check(){if(state.some(v=>v===0))return;const n=l.n,sea=new Set(state.map((v,i)=>v===1?i:-1).filter(i=>i>=0));if(!sea.size)return;for(let r=0;r<n-1;r++)for(let c=0;c<n-1;c++)if([r*n+c,r*n+c+1,(r+1)*n+c,(r+1)*n+c+1].every(i=>sea.has(i)))return;const ss=new Set([sea.values().next().value]),sq=[...ss];while(sq.length){const x=sq.pop(),r=Math.floor(x/n),c=x%n;[[1,0],[-1,0],[0,1],[0,-1]].forEach(([dr,dc])=>{const rr=r+dr,cc=c+dc,j=rr*n+cc;if(rr>=0&&cc>=0&&rr<n&&cc<n&&sea.has(j)&&!ss.has(j)){ss.add(j);sq.push(j);}});}if(ss.size!==sea.size)return;const seen=new Set();for(let i=0;i<n*n;i++){if(state[i]!==2||seen.has(i))continue;const comp=new Set([i]),q=[i];while(q.length){const x=q.pop(),r=Math.floor(x/n),c=x%n;[[1,0],[-1,0],[0,1],[0,-1]].forEach(([dr,dc])=>{const rr=r+dr,cc=c+dc,j=rr*n+cc;if(rr>=0&&cc>=0&&rr<n&&cc<n&&state[j]===2&&!comp.has(j)){comp.add(j);q.push(j);}});}comp.forEach(x=>seen.add(x));const clueCells=[...comp].filter(x=>x in l.clues);if(clueCells.length!==1||l.clues[clueCells[0]]!==comp.size)return;}PK.finish(def,l,t.stop(),hints,opts.daily,launch,run);}
    document.getElementById('nuriClear').onclick=()=>{state.forEach((_,i)=>state[i]=i in l.clues?2:0);render();};document.getElementById('nuriHint').onclick=()=>{const i=state.findIndex((v,j)=>land.has(j)?v!==2:v!==1);if(i>=0){state[i]=land.has(i)?2:1;hints++;render();check();}};render();return()=>t.stop();
  });
})();
